### ISSUE TITLE
to_sql command incompatibility

### ISSUE THREAD

**Issue by ashdsi** [DavidBlocher/mock-data-lab#1]
I get the below error when running this lab

```
cloud_user:~/environment $ python3 mock-data.py
Traceback (most recent call last):
  File "mock-data.py", line 29, in <module>
    df_mock_data.to_sql('users', con=engine,index=False)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2882, in to_sql
    method=method,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 708, in to_sql
    pandas_sql = pandasSQL_builder(con, schema=schema)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 788, in pandasSQL_builder
    return SQLDatabase(con, schema=schema, meta=meta)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1410, in __init__
    meta = MetaData(self.connectable, schema=schema)
TypeError: __init__() got multiple values for argument 'schema'
```

Seems related to the issue here [here](https://stackoverflow.com/questions/75282511/df-to-table-throw-error-typeerror-init-got-multiple-values-for-argument) where latest version of `SQLAlchemy` is not compatible with earlier version of `pandas`. 

These were my versions in the Cloud9 enviornment 

```
cloud_user:~/environment $ pip show sqlalchemy
Name: SQLAlchemy
Version: 2.0.15
```

```
cloud_user:~/environment $ pip show pandas
Name: pandas
Version: 1.3.5
```

**Comment by ashdsi** [comment]
Downgrading to SQLAlchemy 1.4.46 did the trick
```
cloud_user:~/environment $ pip show sqlalchemy
Name: SQLAlchemy
Version: 1.4.46
```
